### Pandas Series

A 1-D labelled array that can store varying data types. The axis labels are called index. Series elements are vertically stacked

pd.Series(data_holder, index = idx) - creates a series of data in the data_holder, with indices in idx

In [6]:
import pandas as pd
import numpy as np

In [7]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([1, 2, 3])
d = {1:10, 2:20, 3:30}

In [8]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr, index = labels)

a    1
b    2
c    3
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

## DataFrames

Several series kept together in parallel

###### Creation - pd.DataFrame(data_holder)
###### Indexing - df2['col_name']  , df[['col1', 'col2']]
###### Add new column - df_name['col_name] = [...values...]
###### Delete column  - df_name.drop([col_names], axeis = 1, inplace=True)    // axis =0 to delete row, inplace false for temp 'deletion'
###### Row selection - df.loc[[rowss]]      // iloc for index location
##### Subset Selectin - df.loc[[rows]][[cols]] 
##### conditional selection - df[df["age"] > 30]

In [11]:
#from dictionary 
data = {
    'Name': ['A', 'B', 'C'],
    'Age' : [1, 2, 3],
    'City': ['a', 'b', 'c'],
    'Sal.': [100, 200, 300]
}

pd.DataFrame(data)

  Name  Age City  Sal.
0    A    1    a   100
1    B    2    b   200
2    C    3    c   300

In [12]:
#from list

col = ['P', 'Q', 'R', 'S']
list1 = [
    ['A', 10, 'abc', 67],
    ['B', 20, 'cde'],
    ['C', 30, 'efg', 3897],
    ['D', 40, 32, 'ijk']
]

df2 = pd.DataFrame(list1)   # no column heading
df2 = pd.DataFrame(list1, columns= col)     #Column headings provided
df2

   P   Q    R     S
0  A  10  abc    67
1  B  20  cde  None
2  C  30  efg  3897
3  D  40   32   ijk

In [21]:
df2['T'] = ["ac", "fgb", "fg", "buh"]        # adding new column
df2['R']                             # display 'R' values

0    abc
1    cde
2    efg
3     32
Name: R, dtype: object

In [25]:
df2[['P', 'S', 'T']]

   P     S    T
0  A    67   ac
1  B  None  fgb
2  C  3897   fg
3  D   ijk  buh

In [26]:
df2.loc[[1, 2]][['P', 'S']]

   P     S
1  B  None
2  C  3897

In [38]:
df2[(df2['Q'] >=20) &  (df2['P'] >= 'C')]

   P   Q    R     S    T
2  C  30  efg  3897   fg
3  D  40   32   ijk  buh